/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutable;

import Listas_clases.ListaPresupuestos;
import Clases.Presupuesto;
import static Ejecutable.IngresoPresupuestos.añoInicio;
import static Ejecutable.IngresoPresupuestos.cantidadAños;
import static Ejecutable.IngresoPresupuestos.crecimientoAnual;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class IngresoPresupuesto extends javax.swing.JFrame {

    /**
     * Creates new form IngresoPresupuesto
     */
    
    public static int añoInicio;
    public static float crecimientoAnual;
    public static int cantidadAños;

    private static DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
   
    public IngresoPresupuesto() {
        initComponents();
        modeloCombo.removeAllElements();
        modeloCombo.addElement("- Seleccionar -");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        texto_crecimiento = new javax.swing.JTextField();
        texto_anio = new javax.swing.JTextField();
        texto_numero_anio = new javax.swing.JTextField();
        aceptar_boton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        rubro = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        registrar_boton = new javax.swing.JButton();
        cajaRubroP = new javax.swing.JTextField();
        valorMonetario = new javax.swing.JTextField();
        cajaTitulo = new javax.swing.JTextField();
        nombreCliente = new javax.swing.JTextField();
        boton_seleccionar = new javax.swing.JComboBox<>();
        eliminar_boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 60, 60));
        jPanel1.setForeground(java.awt.Color.gray);

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingreso de Presupuesto");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de años:");

        jLabel3.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Crecimiento por año:");

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año:");

        texto_crecimiento.setBackground(new java.awt.Color(102, 102, 102));
        texto_crecimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        texto_crecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_crecimientoActionPerformed(evt);
            }
        });

        texto_anio.setBackground(new java.awt.Color(102, 102, 102));
        texto_anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        texto_anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_anioActionPerformed(evt);
            }
        });

        texto_numero_anio.setBackground(new java.awt.Color(102, 102, 102));
        texto_numero_anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        texto_numero_anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_numero_anioActionPerformed(evt);
            }
        });

        aceptar_boton.setBackground(new java.awt.Color(90, 90, 90));
        aceptar_boton.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        aceptar_boton.setForeground(new java.awt.Color(255, 255, 255));
        aceptar_boton.setText("Aceptar");
        aceptar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar_botonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registro de datos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aceptar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texto_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(texto_crecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(texto_numero_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(texto_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(texto_crecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(texto_numero_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aceptar_boton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("NombreCliente:");

        rubro.setBackground(new java.awt.Color(255, 255, 255));
        rubro.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        rubro.setForeground(new java.awt.Color(255, 255, 255));
        rubro.setText("RubroPresupuestal");

        valor.setBackground(new java.awt.Color(255, 255, 255));
        valor.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        valor.setForeground(new java.awt.Color(255, 255, 255));
        valor.setText("Valor Monetario (S/.)");

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Titulo");

        registrar_boton.setBackground(new java.awt.Color(51, 51, 51));
        registrar_boton.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        registrar_boton.setForeground(new java.awt.Color(255, 255, 255));
        registrar_boton.setText("Registrar");
        registrar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_botonActionPerformed(evt);
            }
        });

        cajaRubroP.setBackground(new java.awt.Color(102, 102, 102));
        cajaRubroP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaRubroP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaRubroPActionPerformed(evt);
            }
        });

        valorMonetario.setBackground(new java.awt.Color(102, 102, 102));
        valorMonetario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valorMonetario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorMonetarioActionPerformed(evt);
            }
        });

        cajaTitulo.setBackground(new java.awt.Color(102, 102, 102));
        cajaTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTituloActionPerformed(evt);
            }
        });

        nombreCliente.setBackground(new java.awt.Color(102, 102, 102));
        nombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteActionPerformed(evt);
            }
        });

        boton_seleccionar.setBackground(new java.awt.Color(51, 51, 51));
        boton_seleccionar.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        boton_seleccionar.setForeground(new java.awt.Color(255, 255, 255));
        boton_seleccionar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boton_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_seleccionarActionPerformed(evt);
            }
        });

        eliminar_boton.setBackground(new java.awt.Color(51, 51, 51));
        eliminar_boton.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        eliminar_boton.setForeground(new java.awt.Color(255, 255, 255));
        eliminar_boton.setText("Eliminar");
        eliminar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(valor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(valorMonetario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rubro)
                                        .addComponent(nombre))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cajaRubroP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(titulo)
                                .addGap(155, 155, 155)
                                .addComponent(cajaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(boton_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                                .addComponent(eliminar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(registrar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rubro)
                    .addComponent(cajaRubroP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor)
                    .addComponent(valorMonetario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(cajaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(registrar_boton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar_boton))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texto_crecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_crecimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_crecimientoActionPerformed

    private void texto_anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_anioActionPerformed

    private void texto_numero_anioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_numero_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_numero_anioActionPerformed

    private void aceptar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar_botonActionPerformed
        // TODO add your handling code here:
               
            try{
                if(texto_anio.getText().length() == 4){
                añoInicio = Integer.parseInt(texto_anio.getText());  
                crecimientoAnual = Float.parseFloat(texto_crecimiento.getText());
                cantidadAños = Integer.parseInt(texto_numero_anio.getText());
                
                texto_anio.setEditable(false);
                texto_crecimiento.setEditable(false);
                texto_numero_anio.setEditable(false);
                aceptar_boton.setEnabled(false);
                
                nombreCliente.setEditable(true);
                cajaRubroP.setEditable(true);
                valorMonetario.setEditable(true);
                cajaTitulo.setEditable(true);
                registrar_boton .setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "Año incorrecto",
                    "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
            }    
                }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptar_botonActionPerformed

    private void registrar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_botonActionPerformed
        // TODO add your handling code here:
                try{
            Presupuesto p = new Presupuesto();
           /*
    private String nombreCliente;
    private String rubro;
    private double valorMonetario;
    private String titulo;
    private ArrayList<Double> areas;*/
            p.setNombreCliente(nombreCliente.getText());
            p.setRubro(cajaRubroP.getText());
            p.setValorMonetario(Integer.parseInt(valorMonetario.getText()));
            
            p.setTitulo((cajaTitulo.getText()));
            

            ListaPresupuestos.agregar(p);
            modeloCombo.addElement(p);

            /*cajaAño.setText("Ejm: 2019");
            cajaAño.setForeground(new Color(153,153,153));
            cajaAño.setCaretPosition(0);
            cajaCrecimiento.setText("Ejm: 10");
            cajaCrecimiento.setForeground(new Color(153,153,153));
            cajaCrecimiento.setCaretPosition(0);
            cajaNumAños.setText("Ejm: 5");
            cajaNumAños.setForeground(new Color(153,153,153));
            cajaNumAños.setCaretPosition(0);*/
            nombreCliente.setText("");
            cajaRubroP.setText("");
            valorMonetario.setText("");
            cajaTitulo.setText("-");
            
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_registrar_botonActionPerformed

    private void cajaRubroPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaRubroPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaRubroPActionPerformed

    private void valorMonetarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorMonetarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorMonetarioActionPerformed

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteActionPerformed
        // TODO add your handling code here:
        if(nombreCliente.getText().equals(" ")){

            nombreCliente.setText("");
        }
    }//GEN-LAST:event_nombreClienteActionPerformed

    private void cajaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTituloActionPerformed

    private void eliminar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_botonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_botonActionPerformed

    private void boton_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_seleccionarActionPerformed
        //AA
    }//GEN-LAST:event_boton_seleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar_boton;
    private javax.swing.JComboBox<String> boton_seleccionar;
    private javax.swing.JTextField cajaRubroP;
    private javax.swing.JTextField cajaTitulo;
    private javax.swing.JButton eliminar_boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JButton registrar_boton;
    private javax.swing.JLabel rubro;
    private javax.swing.JTextField texto_anio;
    private javax.swing.JTextField texto_crecimiento;
    private javax.swing.JTextField texto_numero_anio;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel valor;
    private javax.swing.JTextField valorMonetario;
    // End of variables declaration//GEN-END:variables
}
