/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package Ejecutable;

import Listas_clases.ListaPresupuestos;
import Clases.Presupuesto;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Shrike
 */
public class IngresoPresupuestos extends javax.swing.JPanel {
    
    public static int añoInicio;
    public static float crecimientoAnual;
    public static int cantidadAños;

    private static DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    /**
     * Creates new form IngresoPresupuesto
     */
    public IngresoPresupuestos() {
        initComponents();
        
        modeloCombo.removeAllElements();
        modeloCombo.addElement("- Seleccionar -");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        etqAño = new javax.swing.JLabel();
        cajaAño = new javax.swing.JTextField();
        crecimientoAño = new javax.swing.JLabel();
        cajaCrecimiento = new javax.swing.JTextField();
        etqNumAño = new javax.swing.JLabel();
        cajaNumAños = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        etqNombre = new javax.swing.JLabel();
        nombreCliente = new javax.swing.JTextField();
        etqRubro = new javax.swing.JLabel();
        cajaRubroP = new javax.swing.JTextField();
        etqValor = new javax.swing.JLabel();
        valorMonetario = new javax.swing.JTextField();
        etqTitulo = new javax.swing.JLabel();
        cajaTitulo = new javax.swing.JTextField();
        
        botonRegistrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        comboRegistros = new javax.swing.JComboBox<>();
        botonEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridBagLayout());

        etqAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqAño.setText("> Año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(etqAño, gridBagConstraints);

        cajaAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaAño.setForeground(new java.awt.Color(153, 153, 153));
        cajaAño.setText("Ejm: 2019");
        cajaAño.setCaretPosition(0);
        cajaAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaAñoMousePressed(evt);
            }
        });
        cajaAño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaAñoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaAñoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaAño, gridBagConstraints);

        crecimientoAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        crecimientoAño.setText("> Crecimiento por año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(crecimientoAño, gridBagConstraints);

        cajaCrecimiento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaCrecimiento.setForeground(new java.awt.Color(153, 153, 153));
        cajaCrecimiento.setText("Ejm: 10");
        cajaCrecimiento.setCaretPosition(0);
        cajaCrecimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaCrecimientoMousePressed(evt);
            }
        });
        cajaCrecimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaCrecimientoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaCrecimientoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaCrecimiento, gridBagConstraints);

        etqNumAño.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqNumAño.setText("> Numero de años:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(etqNumAño, gridBagConstraints);

        cajaNumAños.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaNumAños.setForeground(new java.awt.Color(153, 153, 153));
        cajaNumAños.setText("Ejm: 5");
        cajaNumAños.setCaretPosition(0);
        cajaNumAños.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaNumAñosMousePressed(evt);
            }
        });
        cajaNumAños.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaNumAñosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaNumAñosKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaNumAños, gridBagConstraints);

        botonAceptar.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(60, 0, 0, 0);
        add(botonAceptar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 80, 0, 80);
        add(jSeparator2, gridBagConstraints);

        etqNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqNombre.setText("> Nombre de Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(etqNombre, gridBagConstraints);

        nombreCliente.setEditable(false);
        nombreCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombreCliente.setForeground(new java.awt.Color(153, 153, 153));
        nombreCliente.setText("");
        nombreCliente.setCaretPosition(0);
        nombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreClienteMousePressed(evt);
            }
        });
        nombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreClienteKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(nombreCliente, gridBagConstraints);

        //Para RubroPresupuestal
        etqRubro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqRubro.setText("> Rubro Presupuestal:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(etqRubro, gridBagConstraints);

        cajaRubroP.setEditable(false);
        cajaRubroP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaRubroP.setForeground(new java.awt.Color(153, 153, 153));
        cajaRubroP.setText("");
        cajaRubroP.setCaretPosition(0);
        cajaRubroP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreClienteMousePressed(evt);
            }
        });
        cajaRubroP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreClienteKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaRubroP, gridBagConstraints);
        
        
        
        etqValor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqValor.setText("> Valor Monetario de Presupuesto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(etqValor, gridBagConstraints);

        valorMonetario.setEditable(false);
        valorMonetario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valorMonetario.setForeground(new java.awt.Color(153, 153, 153));
        valorMonetario.setText("Ejm: S/.250000");
        valorMonetario.setCaretPosition(0);
        valorMonetario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valorMonetarioMousePressed(evt);
            }
        });
        valorMonetario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valorMonetarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorMonetarioKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(valorMonetario, gridBagConstraints);

        etqTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etqTitulo.setText("> Precio de venta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(etqTitulo, gridBagConstraints);

        cajaTitulo.setEditable(false);
        cajaTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaTitulo.setForeground(new java.awt.Color(153, 153, 153));
        cajaTitulo.setText("Ejm: Presupuesto de Obras");
        cajaTitulo.setCaretPosition(0);
        cajaTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaTituloMousePressed(evt);
            }
        });
        cajaTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaTituloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaTituloKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        add(cajaTitulo, gridBagConstraints);

        costoProduccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        costoProduccion.setText("> Costo de producción:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 50, 0, 0);
        add(costoProduccion, gridBagConstraints);

        cajaCosto.setEditable(false);
        cajaCosto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cajaCosto.setForeground(new java.awt.Color(153, 153, 153));
        cajaCosto.setText("Ejm: 11.50");
        cajaCosto.setCaretPosition(0);
        cajaCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaCostoMousePressed(evt);
            }
        });
        cajaCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaCostoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cajaCostoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 50);
        add(cajaCosto, gridBagConstraints);

        botonRegistrar.setFont(new java.awt.Font("Trebuchet MS", 0, 30)); // NOI18N
        botonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap_imagenes/entradaDatos x48.png"))); // NOI18N
        botonRegistrar.setText("Registrar");
        botonRegistrar.setEnabled(false);
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(botonRegistrar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(30, 80, 0, 80);
        add(jSeparator1, gridBagConstraints);

        comboRegistros.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        comboRegistros.setModel(modeloCombo);
        comboRegistros.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboRegistrosPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(36, 70, 0, 0);
        add(comboRegistros, gridBagConstraints);

        botonEliminar.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap_imagenes/basurero x32.png"))); // NOI18N
        botonEliminar.setEnabled(false);
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 80, 0, 0);
        add(botonEliminar, gridBagConstraints);
    }// </editor-fold>                        
    
    
    
    
    
    
    /*
     p.setNombreCliente(cajaDetalle.getText());
            p.setRubro(Integer.parseInt(cajaCantidad.getText()));
            p.setValorMonetario(Float.parseFloat(cajaPrecio.getText()));
            p.setTitulo(Float.parseFloat(cajaCosto.getText()));
    */
        private void cajaRubroPMousePressed(java.awt.event.MouseEvent evt) {                                         
        if(cajaRubroP.getText().equals("Marketing, Gastos, otros ")){

            cajaRubroP.setCaretPosition(0);
        }
    }                                        

     private void cajaRubroPKeyPressed(java.awt.event.KeyEvent evt) {                                       
        if(cajaRubroP.getText().equals(" ")){

            cajaRubroP.setForeground(new Color(0,0,0));
            cajaRubroP.setText("");
        }
    }                                      

    private void cajaRubroPKeyReleased(java.awt.event.KeyEvent evt) {                                        

        if(cajaRubroP.getCaretPosition() == 0 && cajaRubroP.getText().equals("")){

            cajaRubroP.setText(" ");
            cajaRubroP.setForeground(new Color(153,153,153));
            cajaRubroP.setCaretPosition(0);
        }
    }                                             

    
            private void cajaTituloMousePressed(java.awt.event.MouseEvent evt) {                                         
        if(cajaTitulo.getText().equals("Ejemplo: Presupuesto de Obras ")){

            cajaTitulo.setCaretPosition(0);
        }
    }                                        

    private void cajaTituloKeyPressed(java.awt.event.KeyEvent evt) {                                       
        if(cajaTitulo.getText().equals(" ")){

            cajaTitulo.setForeground(new Color(0,0,0));
            cajaTitulo.setText("");
        }
    }                                      

    private void cajaTituloKeyReleased(java.awt.event.KeyEvent evt) {                                        

        if(cajaTitulo.getCaretPosition() == 0 && cajaTitulo.getText().equals("")){

            cajaTitulo.setText("Ejemplo: Presupuesto de Obras ");
            cajaTitulo.setForeground(new Color(153,153,153));
            cajaTitulo.setCaretPosition(0);
        }
    }                                             
    
    private void nombreClienteMousePressed(java.awt.event.MouseEvent evt) {                                         
        if(nombreCliente.getText().equals(" ")){

            nombreCliente.setCaretPosition(0);
        }
    }                                        

    private void nombreClienteKeyPressed(java.awt.event.KeyEvent evt) {                                       
        if(nombreCliente.getText().equals(" ")){

            nombreCliente.setForeground(new Color(0,0,0));
            nombreCliente.setText("");
        }
    }                                      

    private void nombreClienteKeyReleased(java.awt.event.KeyEvent evt) {                                        

        if(nombreCliente.getCaretPosition() == 0 && nombreCliente.getText().equals("")){

            nombreCliente.setText(" ");
            nombreCliente.setForeground(new Color(153,153,153));
            nombreCliente.setCaretPosition(0);
        }
    }                                             

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {                                               

        try{
            Presupuesto p = new Presupuesto();
           /*
    private String nombreCliente;
    private String rubro;
    private double valorMonetario;
    private String titulo;
    private ArrayList<Double> areas;*/
            p.setNombreCliente(nombreCliente.getText());
            p.setRubro(cajaRubroP.getText());
            p.setValorMonetario(Integer.parseInt(valorMonetario.getText()));
            
            p.setTitulo((cajaTitulo.getText()));
            

            ListaPresupuestos.agregar(p);
            modeloCombo.addElement(p);

            /*cajaAño.setText("Ejm: 2019");
            cajaAño.setForeground(new Color(153,153,153));
            cajaAño.setCaretPosition(0);
            cajaCrecimiento.setText("Ejm: 10");
            cajaCrecimiento.setForeground(new Color(153,153,153));
            cajaCrecimiento.setCaretPosition(0);
            cajaNumAños.setText("Ejm: 5");
            cajaNumAños.setForeground(new Color(153,153,153));
            cajaNumAños.setCaretPosition(0);*/
            nombreCliente.setText("");
            nombreCliente.setForeground(new Color(153,153,153));
            nombreCliente.setCaretPosition(0);
            cajaRubroP.setText("Ejm: Marketing, Gastos, otros");
            cajaRubroP.setForeground(new Color(153,153,153));
            cajaRubroP.setCaretPosition(0);
            valorMonetario.setText("Ejm: S/.150000");
            valorMonetario.setForeground(new Color(153,153,153));
            valorMonetario.setCaretPosition(0);
            cajaTitulo.setText("-");
            cajaTitulo.setForeground(new Color(153,153,153));
            cajaTitulo.setCaretPosition(0);
            
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }                                              

    private void comboRegistrosPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                            
        if(comboRegistros.getSelectedIndex() == 0){
            botonEliminar.setEnabled(false);
        }else{
            botonEliminar.setEnabled(true);
        }
    }                                                           

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try{
            
            ListaPresupuestos.eliminar((Presupuesto)comboRegistros.getSelectedItem());
            
            modeloCombo.removeElementAt(comboRegistros.getSelectedIndex());
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }                                             

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        try{
            if(cajaAño.getText().length() == 4){
                añoInicio = Integer.parseInt(cajaAño.getText());  
                crecimientoAnual = Float.parseFloat(cajaCrecimiento.getText());
                cantidadAños = Integer.parseInt(cajaNumAños.getText());
                
                cajaAño.setEditable(false);
                cajaCrecimiento.setEditable(false);
                cajaNumAños.setEditable(false);
                botonAceptar.setEnabled(false);
                
                nombreCliente.setEditable(true);
                cajaRubroP.setEditable(true);
                valorMonetario.setEditable(true);
                cajaTitulo.setEditable(true);
                botonRegistrar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(this, "Año incorrecto",
                    "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception  error){
            JOptionPane.showMessageDialog(this, error.getMessage(),
                "ERROR DEL SISTEMA", JOptionPane.ERROR_MESSAGE);
        }
    }                                            

    private void cajaAñoMousePressed(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        if(cajaAño.getText().equals("Ejm: 2019")){

            cajaAño.setCaretPosition(0);
        }
    }                                    

    private void cajaAñoKeyPressed(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
        if(cajaAño.getText().equals("Ejm: 2019")){

            cajaAño.setForeground(new Color(0,0,0));
            cajaAño.setText("");
        }
    }                                  

    private void cajaAñoKeyReleased(java.awt.event.KeyEvent evt) {                                    
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaAño.getCaretPosition() == 0 && cajaAño.getText().equals("")){

            cajaAño.setText("Ejm: 2019");
            cajaAño.setForeground(new Color(153,153,153));
            cajaAño.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaAño.getText().length(); i++) {
                char c = cajaAño.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaAño.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaAño.setForeground(new Color(0,0,0)); // negro
            }
        }
    }                                   

    private void cajaCrecimientoMousePressed(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        if(cajaCrecimiento.getText().equals("Ejm: 10")){

            cajaCrecimiento.setCaretPosition(0);
        }
    }                                            

    private void cajaCrecimientoKeyPressed(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        if(cajaCrecimiento.getText().equals("Ejm: 10")){

            cajaCrecimiento.setForeground(new Color(0,0,0));
            cajaCrecimiento.setText("");
        }
    }                                          

    private void cajaCrecimientoKeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaCrecimiento.getCaretPosition() == 0 && cajaCrecimiento.getText().equals("")){

            cajaCrecimiento.setText("Ejm: 10");
            cajaCrecimiento.setForeground(new Color(153,153,153));
            cajaCrecimiento.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaCrecimiento.getText().length(); i++) {
                char c = cajaCrecimiento.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0' && c != '.'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaCrecimiento.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaCrecimiento.setForeground(new Color(0,0,0)); // negro
            }
        }
    }                                           

    private void cajaNumAñosMousePressed(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        if(cajaNumAños.getText().equals("Ejm: 5")){

            cajaNumAños.setCaretPosition(0);
        }
    }                                        

    private void cajaNumAñosKeyPressed(java.awt.event.KeyEvent evt) {                                       
        // TODO add your handling code here:
        if(cajaNumAños.getText().equals("Ejm: 5")){

            cajaNumAños.setForeground(new Color(0,0,0));
            cajaNumAños.setText("");
        }
    }                                      

    private void cajaNumAñosKeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaNumAños.getCaretPosition() == 0 && cajaNumAños.getText().equals("")){

            cajaNumAños.setText("Ejm: 5");
            cajaNumAños.setForeground(new Color(153,153,153));
            cajaNumAños.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaNumAños.getText().length(); i++) {
                char c = cajaNumAños.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaNumAños.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaNumAños.setForeground(new Color(0,0,0)); // negro
            }
        }
    }                                       
    
       private void valorMonetarioMousePressed(java.awt.event.MouseEvent evt) {                                          

        if(valorMonetario.getText().equals("Ejm: s/.25000000")){

            valorMonetario.setCaretPosition(0);
        }
    }                                         

    private void valorMonetarioKeyPressed(java.awt.event.KeyEvent evt) {                                        

        if(valorMonetario.getText().equals("Ejm: 2500")){

            valorMonetario.setForeground(new Color(0,0,0));
            valorMonetario.setText("");
        }
    }                                       

    private void valorMonetarioKeyReleased(java.awt.event.KeyEvent evt) {                                         
        boolean letra = false;

        if(valorMonetario.getCaretPosition() == 0 && valorMonetario.getText().equals("")){

            valorMonetario.setText("Ejm: 2500");
            valorMonetario.setForeground(new Color(153,153,153));
            valorMonetario.setCaretPosition(0);
        }else{

            for (int i = 0; i < valorMonetario.getText().length(); i++) {
                char c = valorMonetario.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0'){

                    letra = true;
                }
            }

            if(letra == true){
                valorMonetario.setForeground(new Color(255,51,51)); // rojo
            }else{
                valorMonetario.setForeground(new Color(0,0,0)); // negro
            }
        }
    }                                        
    
    private void cajaCostoMousePressed(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        if(cajaCosto.getText().equals("Ejm: 11.50")){

            cajaCosto.setCaretPosition(0);
        }
    }                                      

    private void cajaCostoKeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        if(cajaCosto.getText().equals("Ejm: 11.50")){

            cajaCosto.setForeground(new Color(0,0,0));
            cajaCosto.setText("");
        }
    }                                    

    private void cajaCostoKeyReleased(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        boolean letra = false;

        if(cajaCosto.getCaretPosition() == 0 && cajaCosto.getText().equals("")){

            cajaCosto.setText("Ejm: 11.50");
            cajaCosto.setForeground(new Color(153,153,153));
            cajaCosto.setCaretPosition(0);
        }else{

            for (int i = 0; i < cajaCosto.getText().length(); i++) {
                char c = cajaCosto.getText().charAt(i);

                if(c != '1' && c != '2' && c != '3' && c != '4' && c != '5'
                    && c != '6' && c != '7' && c != '8' && c != '9' && c != '0' && c != '.'){

                    letra = true;
                }
            }

            if(letra == true){
                cajaCosto.setForeground(new Color(255,51,51)); // rojo
            }else{
                cajaCosto.setForeground(new Color(0,0,0)); // negro
            }
        }
    }                                     
    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField cajaAño;
    private javax.swing.JTextField cajaRubroP;
    private javax.swing.JTextField valorMonetario;
    private javax.swing.JTextField cajaCosto;
    private javax.swing.JTextField cajaCrecimiento;
    private javax.swing.JTextField nombreCliente;
    private javax.swing.JTextField cajaNumAños;
    private javax.swing.JTextField cajaTitulo;
    private javax.swing.JComboBox<String> comboRegistros;
    private javax.swing.JLabel costoProduccion;
    private javax.swing.JLabel crecimientoAño;
    private javax.swing.JLabel etqAño;
    private javax.swing.JLabel etqValor;
    private javax.swing.JLabel etqRubro;
    private javax.swing.JLabel etqNombre;
    private javax.swing.JLabel etqNumAño;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    
}